// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAc9aCZbxmBpBUtD4Ioc4uPtPYmAHfmUI',
    appId: '1:150621838045:web:b2820ae99a1da0cde29934',
    messagingSenderId: '150621838045',
    projectId: 'chat-app-85d6f',
    authDomain: 'chat-app-85d6f.firebaseapp.com',
    storageBucket: 'chat-app-85d6f.firebasestorage.app',
    measurementId: 'G-XC0T499SGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sdHbNRgrw3eBmtXg3ayPjzjYk0LKLjw',
    appId: '1:150621838045:android:7c17814e19e7625ae29934',
    messagingSenderId: '150621838045',
    projectId: 'chat-app-85d6f',
    storageBucket: 'chat-app-85d6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBbSxlCd_--Z3rRzm6qZ2DfDyI-F01uo',
    appId: '1:150621838045:ios:53b1c488923cbf22e29934',
    messagingSenderId: '150621838045',
    projectId: 'chat-app-85d6f',
    storageBucket: 'chat-app-85d6f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEBbSxlCd_--Z3rRzm6qZ2DfDyI-F01uo',
    appId: '1:150621838045:ios:53b1c488923cbf22e29934',
    messagingSenderId: '150621838045',
    projectId: 'chat-app-85d6f',
    storageBucket: 'chat-app-85d6f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAc9aCZbxmBpBUtD4Ioc4uPtPYmAHfmUI',
    appId: '1:150621838045:web:66f034b504b9de31e29934',
    messagingSenderId: '150621838045',
    projectId: 'chat-app-85d6f',
    authDomain: 'chat-app-85d6f.firebaseapp.com',
    storageBucket: 'chat-app-85d6f.firebasestorage.app',
    measurementId: 'G-NLGC3GJL10',
  );
}
